package com.example.myapplication

import android.annotation.SuppressLint
import android.os.Bundle
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import com.example.myapplication.databinding.FragmentMainBinding
import com.google.gson.Gson
import com.google.gson.reflect.TypeToken


class MainFragment : Fragment() {
    lateinit var binding: FragmentMainBinding
    var i = 0

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
    }

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        binding = FragmentMainBinding.inflate(layoutInflater, container, false)
        return binding.root
    }

    @SuppressLint("NotifyDataSetChanged")
    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        val customerJson = """
       [{
		"ID": 8718,
		"Code": "2113127",
		"FromToNameAndCompany": "- اینان ",
		"FirstCompanyName": "- اینان",
		"LastName": null,
		"FirstCompanyNameEng": null,
		"LastNameEng": null,
		"Name": "- اینان ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": null,
		"Email": null,
		"PhoneNumber": null,
		"Mobile": null,
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11563,
		"Code": "2116002",
		"FromToNameAndCompany": " بیمارستان نبی اکرم ",
		"FirstCompanyName": " بیمارستان نبی اکرم",
		"LastName": null,
		"FirstCompanyNameEng": "",
		"LastNameEng": null,
		"Name": " بیمارستان نبی اکرم ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": "",
		"Email": "",
		"PhoneNumber": "",
		"Mobile": "",
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 8683,
		"Code": "2113091",
		"FromToNameAndCompany": "- حق التدریس ",
		"FirstCompanyName": "- حق التدریس",
		"LastName": null,
		"FirstCompanyNameEng": null,
		"LastNameEng": null,
		"Name": "- حق التدریس ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": null,
		"Email": null,
		"PhoneNumber": null,
		"Mobile": null,
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11522,
		"Code": "2115956",
		"FromToNameAndCompany": " خانه ایمپلنت تهرانسر ",
		"FirstCompanyName": " خانه ایمپلنت تهرانسر",
		"LastName": null,
		"FirstCompanyNameEng": "",
		"LastNameEng": null,
		"Name": " خانه ایمپلنت تهرانسر ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": "",
		"Email": "",
		"PhoneNumber": "",
		"Mobile": "",
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11499,
		"Code": "2115931",
		"FromToNameAndCompany": " دانشگاه علوم پزشکی بقیه الله ",
		"FirstCompanyName": " دانشگاه علوم پزشکی بقیه الله",
		"LastName": null,
		"FirstCompanyNameEng": "",
		"LastNameEng": null,
		"Name": " دانشگاه علوم پزشکی بقیه الله ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": "",
		"Email": "",
		"PhoneNumber": "",
		"Mobile": "",
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11556,
		"Code": "2115994",
		"FromToNameAndCompany": " درمانگاه امیرالمونین ",
		"FirstCompanyName": " درمانگاه امیرالمونین",
		"LastName": null,
		"FirstCompanyNameEng": "",
		"LastNameEng": null,
		"Name": " درمانگاه امیرالمونین ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": "",
		"Email": "",
		"PhoneNumber": "",
		"Mobile": "",
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11569,
		"Code": "2116009",
		"FromToNameAndCompany": " درمانگاه بهارا ",
		"FirstCompanyName": " درمانگاه بهارا",
		"LastName": null,
		"FirstCompanyNameEng": "",
		"LastNameEng": null,
		"Name": " درمانگاه بهارا ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": "",
		"Email": "",
		"PhoneNumber": "",
		"Mobile": "",
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11362,
		"Code": "2115778",
		"FromToNameAndCompany": " درمانگاه خیریه موسی ابن جعفر ",
		"FirstCompanyName": " درمانگاه خیریه موسی ابن جعفر",
		"LastName": null,
		"FirstCompanyNameEng": "",
		"LastNameEng": null,
		"Name": " درمانگاه خیریه موسی ابن جعفر ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": "",
		"Email": "",
		"PhoneNumber": "",
		"Mobile": "",
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11535,
		"Code": "2115969",
		"FromToNameAndCompany": " درمانگاه دارالشفاء امام محمد باقر ",
		"FirstCompanyName": " درمانگاه دارالشفاء امام محمد باقر",
		"LastName": null,
		"FirstCompanyNameEng": "",
		"LastNameEng": null,
		"Name": " درمانگاه دارالشفاء امام محمد باقر ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": "",
		"Email": "",
		"PhoneNumber": "",
		"Mobile": "",
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11343,
		"Code": "2115758",
		"FromToNameAndCompany": " درمانگاه شهید بهشتی ",
		"FirstCompanyName": " درمانگاه شهید بهشتی",
		"LastName": null,
		"FirstCompanyNameEng": "",
		"LastNameEng": null,
		"Name": " درمانگاه شهید بهشتی ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": "",
		"Email": "",
		"PhoneNumber": "",
		"Mobile": "",
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11471,
		"Code": "2115890",
		"FromToNameAndCompany": " درمانگاه قطب الدین ",
		"FirstCompanyName": " درمانگاه قطب الدین",
		"LastName": null,
		"FirstCompanyNameEng": "",
		"LastNameEng": null,
		"Name": " درمانگاه قطب الدین ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": "",
		"Email": "",
		"PhoneNumber": "",
		"Mobile": "",
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11271,
		"Code": "2115684",
		"FromToNameAndCompany": " درمانگاه ولیعصر ",
		"FirstCompanyName": " درمانگاه ولیعصر",
		"LastName": null,
		"FirstCompanyNameEng": "",
		"LastNameEng": null,
		"Name": " درمانگاه ولیعصر ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": "",
		"Email": "",
		"PhoneNumber": "",
		"Mobile": "",
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11479,
		"Code": "2115899",
		"FromToNameAndCompany": " درمانگاه کربلا ",
		"FirstCompanyName": " درمانگاه کربلا",
		"LastName": null,
		"FirstCompanyNameEng": "",
		"LastNameEng": null,
		"Name": " درمانگاه کربلا ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": "",
		"Email": "",
		"PhoneNumber": "",
		"Mobile": "",
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11269,
		"Code": "2115682",
		"FromToNameAndCompany": " درمانگاه کمیل ",
		"FirstCompanyName": " درمانگاه کمیل",
		"LastName": null,
		"FirstCompanyNameEng": "",
		"LastNameEng": null,
		"Name": " درمانگاه کمیل ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": "",
		"Email": "",
		"PhoneNumber": "",
		"Mobile": "",
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11415,
		"Code": "2115833",
		"FromToNameAndCompany": " دندانپزشکی میلاد ",
		"FirstCompanyName": " دندانپزشکی میلاد",
		"LastName": null,
		"FirstCompanyNameEng": "",
		"LastNameEng": null,
		"Name": " دندانپزشکی میلاد ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": "",
		"Email": "",
		"PhoneNumber": "",
		"Mobile": "",
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11292,
		"Code": "2115706",
		"FromToNameAndCompany": " شرکت بهبود سلامت حکیم رفسنجان ",
		"FirstCompanyName": " شرکت بهبود سلامت حکیم رفسنجان",
		"LastName": null,
		"FirstCompanyNameEng": "",
		"LastNameEng": null,
		"Name": " شرکت بهبود سلامت حکیم رفسنجان ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": "",
		"Email": "",
		"PhoneNumber": "",
		"Mobile": "",
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11283,
		"Code": "2115697",
		"FromToNameAndCompany": " شرکت مینا گران برنا ",
		"FirstCompanyName": " شرکت مینا گران برنا",
		"LastName": null,
		"FirstCompanyNameEng": "",
		"LastNameEng": null,
		"Name": " شرکت مینا گران برنا ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": "",
		"Email": "",
		"PhoneNumber": "",
		"Mobile": "",
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 8716,
		"Code": "2113125",
		"FromToNameAndCompany": "- صفا ",
		"FirstCompanyName": "- صفا",
		"LastName": null,
		"FirstCompanyNameEng": null,
		"LastNameEng": null,
		"Name": "- صفا ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": null,
		"Email": null,
		"PhoneNumber": null,
		"Mobile": null,
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 8720,
		"Code": "2113129",
		"FromToNameAndCompany": "- ظریف ",
		"FirstCompanyName": "- ظریف",
		"LastName": null,
		"FirstCompanyNameEng": null,
		"LastNameEng": null,
		"Name": "- ظریف ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": null,
		"Email": null,
		"PhoneNumber": null,
		"Mobile": null,
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 8717,
		"Code": "2113126",
		"FromToNameAndCompany": "- قربان ",
		"FirstCompanyName": "- قربان",
		"LastName": null,
		"FirstCompanyNameEng": null,
		"LastNameEng": null,
		"Name": "- قربان ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": null,
		"Email": null,
		"PhoneNumber": null,
		"Mobile": null,
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 12723,
		"Code": "2116905",
		"FromToNameAndCompany": " مهدی نیکخواه ",
		"FirstCompanyName": " مهدی نیکخواه",
		"LastName": null,
		"FirstCompanyNameEng": "",
		"LastNameEng": null,
		"Name": " مهدی نیکخواه ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": "",
		"Email": "",
		"PhoneNumber": "",
		"Mobile": "",
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11419,
		"Code": "2115837",
		"FromToNameAndCompany": " موسسه خیریه و دارالشفاء ثامن الائمه ",
		"FirstCompanyName": " موسسه خیریه و دارالشفاء ثامن الائمه",
		"LastName": null,
		"FirstCompanyNameEng": null,
		"LastNameEng": null,
		"Name": " موسسه خیریه و دارالشفاء ثامن الائمه ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": null,
		"Email": null,
		"PhoneNumber": null,
		"Mobile": null,
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11454,
		"Code": "2115873",
		"FromToNameAndCompany": " موسسه درمانی آستان قدس رضوی ",
		"FirstCompanyName": " موسسه درمانی آستان قدس رضوی",
		"LastName": null,
		"FirstCompanyNameEng": "",
		"LastNameEng": null,
		"Name": " موسسه درمانی آستان قدس رضوی ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": "",
		"Email": "",
		"PhoneNumber": "",
		"Mobile": "",
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11325,
		"Code": "2115739",
		"FromToNameAndCompany": " کلینیک اکسین ",
		"FirstCompanyName": " کلینیک اکسین",
		"LastName": null,
		"FirstCompanyNameEng": "",
		"LastNameEng": null,
		"Name": " کلینیک اکسین ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": "",
		"Email": "",
		"PhoneNumber": "",
		"Mobile": "",
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11396,
		"Code": "2115814",
		"FromToNameAndCompany": " کلینیک ایده ",
		"FirstCompanyName": " کلینیک ایده",
		"LastName": null,
		"FirstCompanyNameEng": "",
		"LastNameEng": null,
		"Name": " کلینیک ایده ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": "",
		"Email": "",
		"PhoneNumber": "",
		"Mobile": "",
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11333,
		"Code": "2115747",
		"FromToNameAndCompany": " کلینیک پردیس ",
		"FirstCompanyName": " کلینیک پردیس",
		"LastName": null,
		"FirstCompanyNameEng": null,
		"LastNameEng": null,
		"Name": " کلینیک پردیس ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": null,
		"Email": null,
		"PhoneNumber": null,
		"Mobile": null,
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11457,
		"Code": "2115876",
		"FromToNameAndCompany": " کلینیک تخصصی رضایی ",
		"FirstCompanyName": " کلینیک تخصصی رضایی",
		"LastName": null,
		"FirstCompanyNameEng": null,
		"LastNameEng": null,
		"Name": " کلینیک تخصصی رضایی ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": null,
		"Email": null,
		"PhoneNumber": null,
		"Mobile": null,
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11429,
		"Code": "2115848",
		"FromToNameAndCompany": " کلینیک تخصصی مهر ساوه ",
		"FirstCompanyName": " کلینیک تخصصی مهر ساوه",
		"LastName": null,
		"FirstCompanyNameEng": null,
		"LastNameEng": null,
		"Name": " کلینیک تخصصی مهر ساوه ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": null,
		"Email": null,
		"PhoneNumber": null,
		"Mobile": null,
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11284,
		"Code": "2115698",
		"FromToNameAndCompany": " کلینیک دندانپزشکی آرامیس ",
		"FirstCompanyName": " کلینیک دندانپزشکی آرامیس",
		"LastName": null,
		"FirstCompanyNameEng": null,
		"LastNameEng": null,
		"Name": " کلینیک دندانپزشکی آرامیس ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": null,
		"Email": null,
		"PhoneNumber": null,
		"Mobile": null,
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11519,
		"Code": "2115953",
		"FromToNameAndCompany": " کلینیک دندانپزشکی برگ ",
		"FirstCompanyName": " کلینیک دندانپزشکی برگ",
		"LastName": null,
		"FirstCompanyNameEng": null,
		"LastNameEng": null,
		"Name": " کلینیک دندانپزشکی برگ ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": null,
		"Email": null,
		"PhoneNumber": null,
		"Mobile": null,
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11405,
		"Code": "2115823",
		"FromToNameAndCompany": " کلینیک دندانپزشکی برلیان ",
		"FirstCompanyName": " کلینیک دندانپزشکی برلیان",
		"LastName": null,
		"FirstCompanyNameEng": null,
		"LastNameEng": null,
		"Name": " کلینیک دندانپزشکی برلیان ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": null,
		"Email": null,
		"PhoneNumber": null,
		"Mobile": null,
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11445,
		"Code": "2115864",
		"FromToNameAndCompany": " کلینیک دندانپزشکی جهاد دانشگاهی ",
		"FirstCompanyName": " کلینیک دندانپزشکی جهاد دانشگاهی",
		"LastName": null,
		"FirstCompanyNameEng": null,
		"LastNameEng": null,
		"Name": " کلینیک دندانپزشکی جهاد دانشگاهی ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": null,
		"Email": null,
		"PhoneNumber": null,
		"Mobile": null,
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11332,
		"Code": "2115746",
		"FromToNameAndCompany": " کلینیک دندانپزشکی حصارک ",
		"FirstCompanyName": " کلینیک دندانپزشکی حصارک",
		"LastName": null,
		"FirstCompanyNameEng": null,
		"LastNameEng": null,
		"Name": " کلینیک دندانپزشکی حصارک ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": null,
		"Email": null,
		"PhoneNumber": null,
		"Mobile": null,
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11387,
		"Code": "2115805",
		"FromToNameAndCompany": " کلینیک دندانپزشکی دنا (شرکت تعاونی 635) ",
		"FirstCompanyName": " کلینیک دندانپزشکی دنا (شرکت تعاونی 635)",
		"LastName": null,
		"FirstCompanyNameEng": null,
		"LastNameEng": null,
		"Name": " کلینیک دندانپزشکی دنا (شرکت تعاونی 635) ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": null,
		"Email": null,
		"PhoneNumber": null,
		"Mobile": null,
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11317,
		"Code": "2115731",
		"FromToNameAndCompany": " کلینیک دندانپزشکی شاهد ",
		"FirstCompanyName": " کلینیک دندانپزشکی شاهد",
		"LastName": null,
		"FirstCompanyNameEng": null,
		"LastNameEng": null,
		"Name": " کلینیک دندانپزشکی شاهد ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": null,
		"Email": null,
		"PhoneNumber": null,
		"Mobile": null,
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11393,
		"Code": "2115811",
		"FromToNameAndCompany": " کلینیک دندانپزشکی شریعتی ",
		"FirstCompanyName": " کلینیک دندانپزشکی شریعتی",
		"LastName": null,
		"FirstCompanyNameEng": null,
		"LastNameEng": null,
		"Name": " کلینیک دندانپزشکی شریعتی ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": null,
		"Email": null,
		"PhoneNumber": null,
		"Mobile": null,
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11557,
		"Code": "2115995",
		"FromToNameAndCompany": " کلینیک دکتر دنتال ",
		"FirstCompanyName": " کلینیک دکتر دنتال",
		"LastName": null,
		"FirstCompanyNameEng": null,
		"LastNameEng": null,
		"Name": " کلینیک دکتر دنتال ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": null,
		"Email": null,
		"PhoneNumber": null,
		"Mobile": null,
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11555,
		"Code": "2115993",
		"FromToNameAndCompany": " کلینیک دیبا ",
		"FirstCompanyName": " کلینیک دیبا",
		"LastName": null,
		"FirstCompanyNameEng": null,
		"LastNameEng": null,
		"Name": " کلینیک دیبا ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": null,
		"Email": null,
		"PhoneNumber": null,
		"Mobile": null,
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11517,
		"Code": "2115951",
		"FromToNameAndCompany": " کلینیک رسا ",
		"FirstCompanyName": " کلینیک رسا",
		"LastName": null,
		"FirstCompanyNameEng": null,
		"LastNameEng": null,
		"Name": " کلینیک رسا ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": null,
		"Email": null,
		"PhoneNumber": null,
		"Mobile": null,
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11544,
		"Code": "2115979",
		"FromToNameAndCompany": " کلینیک ستاره ",
		"FirstCompanyName": " کلینیک ستاره",
		"LastName": null,
		"FirstCompanyNameEng": null,
		"LastNameEng": null,
		"Name": " کلینیک ستاره ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": null,
		"Email": null,
		"PhoneNumber": null,
		"Mobile": null,
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11397,
		"Code": "2115815",
		"FromToNameAndCompany": " کلینیک عاج ",
		"FirstCompanyName": " کلینیک عاج",
		"LastName": null,
		"FirstCompanyNameEng": null,
		"LastNameEng": null,
		"Name": " کلینیک عاج ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": null,
		"Email": null,
		"PhoneNumber": null,
		"Mobile": null,
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11488,
		"Code": "2115919",
		"FromToNameAndCompany": " کلینیک عقیق ",
		"FirstCompanyName": " کلینیک عقیق",
		"LastName": null,
		"FirstCompanyNameEng": null,
		"LastNameEng": null,
		"Name": " کلینیک عقیق ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": null,
		"Email": null,
		"PhoneNumber": null,
		"Mobile": null,
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11460,
		"Code": "2115879",
		"FromToNameAndCompany": " کلینیک لبخند سفید ",
		"FirstCompanyName": " کلینیک لبخند سفید",
		"LastName": null,
		"FirstCompanyNameEng": null,
		"LastNameEng": null,
		"Name": " کلینیک لبخند سفید ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": null,
		"Email": null,
		"PhoneNumber": null,
		"Mobile": null,
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11270,
		"Code": "2115683",
		"FromToNameAndCompany": " کلینیک مهرگان ",
		"FirstCompanyName": " کلینیک مهرگان",
		"LastName": null,
		"FirstCompanyNameEng": null,
		"LastNameEng": null,
		"Name": " کلینیک مهرگان ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": null,
		"Email": null,
		"PhoneNumber": null,
		"Mobile": null,
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11502,
		"Code": "2115935",
		"FromToNameAndCompany": " کلینیک نور ",
		"FirstCompanyName": " کلینیک نور",
		"LastName": null,
		"FirstCompanyNameEng": null,
		"LastNameEng": null,
		"Name": " کلینیک نور ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": null,
		"Email": null,
		"PhoneNumber": null,
		"Mobile": null,
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11553,
		"Code": "2115991",
		"FromToNameAndCompany": " کلینیک کیمیا ",
		"FirstCompanyName": " کلینیک کیمیا",
		"LastName": null,
		"FirstCompanyNameEng": null,
		"LastNameEng": null,
		"Name": " کلینیک کیمیا ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": null,
		"Email": null,
		"PhoneNumber": null,
		"Mobile": null,
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11785,
		"Code": "04",
		"FromToNameAndCompany": "Aquapick ",
		"FirstCompanyName": "Aquapick",
		"LastName": null,
		"FirstCompanyNameEng": "",
		"LastNameEng": null,
		"Name": "Aquapick ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": "",
		"Email": "",
		"PhoneNumber": "",
		"Mobile": "",
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "تامین کننده",
		"CompanyName": null
	}, {
		"ID": 13711,
		"Code": "02",
		"FromToNameAndCompany": "Botiss ",
		"FirstCompanyName": "Botiss",
		"LastName": null,
		"FirstCompanyNameEng": "",
		"LastNameEng": null,
		"Name": "Botiss ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": "",
		"Email": "",
		"PhoneNumber": "",
		"Mobile": "",
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "تامین کننده",
		"CompanyName": null
	}, {
		"ID": 12322,
		"Code": "03",
		"FromToNameAndCompany": "Dio ",
		"FirstCompanyName": "Dio",
		"LastName": null,
		"FirstCompanyNameEng": "",
		"LastNameEng": null,
		"Name": "Dio ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": "",
		"Email": "",
		"PhoneNumber": "",
		"Mobile": "",
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "تامین کننده",
		"CompanyName": null
	}, {
		"ID": 10491,
		"Code": "2114904",
		"FromToNameAndCompany": "test test ",
		"FirstCompanyName": "test test",
		"LastName": null,
		"FirstCompanyNameEng": null,
		"LastNameEng": null,
		"Name": "test test ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": null,
		"Email": null,
		"PhoneNumber": null,
		"Mobile": null,
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 15027,
		"Code": "2117619",
		"FromToNameAndCompany": "آئین به فلاحی ",
		"FirstCompanyName": "آئین به فلاحی",
		"LastName": "",
		"FirstCompanyNameEng": "",
		"LastNameEng": "",
		"Name": "آئین به فلاحی ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": "",
		"Email": "",
		"PhoneNumber": "",
		"Mobile": "",
		"AreaID": null,
		"DetailCode": "",
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": "",
		"Position": "",
		"NationalID": "",
		"RegistrationNumber": "",
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 15683,
		"Code": "2117856",
		"FromToNameAndCompany": "آبتین صادقی ",
		"FirstCompanyName": "آبتین صادقی",
		"LastName": "",
		"FirstCompanyNameEng": "",
		"LastNameEng": "",
		"Name": "آبتین صادقی ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": "",
		"Email": "",
		"PhoneNumber": "",
		"Mobile": "",
		"AreaID": null,
		"DetailCode": "",
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": "",
		"Position": "",
		"NationalID": "",
		"RegistrationNumber": "",
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11505,
		"Code": "2115938",
		"FromToNameAndCompany": "آتنا افضلی مهر ",
		"FirstCompanyName": "آتنا افضلی مهر",
		"LastName": null,
		"FirstCompanyNameEng": null,
		"LastNameEng": null,
		"Name": "آتنا افضلی مهر ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": null,
		"Email": null,
		"PhoneNumber": null,
		"Mobile": null,
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": null,
		"CompanyName": null
	}, {
		"ID": 15599,
		"Code": "6112243",
		"FromToNameAndCompany": "آتنا معنوی ",
		"FirstCompanyName": "آتنا معنوی",
		"LastName": "",
		"FirstCompanyNameEng": "",
		"LastNameEng": "",
		"Name": "آتنا معنوی ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": "",
		"Email": "",
		"PhoneNumber": "",
		"Mobile": "",
		"AreaID": null,
		"DetailCode": "",
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": "",
		"Position": "",
		"NationalID": "",
		"RegistrationNumber": "",
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 8008,
		"Code": "2112408",
		"FromToNameAndCompany": "آتوسا باقری ",
		"FirstCompanyName": "آتوسا باقری",
		"LastName": null,
		"FirstCompanyNameEng": null,
		"LastNameEng": null,
		"Name": "آتوسا باقری ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": null,
		"Email": null,
		"PhoneNumber": null,
		"Mobile": null,
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 6674,
		"Code": "2111052",
		"FromToNameAndCompany": "آتوسا طالبی ",
		"FirstCompanyName": "آتوسا طالبی",
		"LastName": null,
		"FirstCompanyNameEng": null,
		"LastNameEng": null,
		"Name": "آتوسا طالبی ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": null,
		"Email": null,
		"PhoneNumber": null,
		"Mobile": null,
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 11257,
		"Code": "2115670",
		"FromToNameAndCompany": "آتوسا طالبی ",
		"FirstCompanyName": "آتوسا طالبی",
		"LastName": null,
		"FirstCompanyNameEng": null,
		"LastNameEng": null,
		"Name": "آتوسا طالبی ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": null,
		"Email": null,
		"PhoneNumber": null,
		"Mobile": null,
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 15302,
		"Code": "2117727",
		"FromToNameAndCompany": "آتیه درمان و دندان صفرعلی زاده ",
		"FirstCompanyName": "آتیه درمان و دندان صفرعلی زاده",
		"LastName": "",
		"FirstCompanyNameEng": "",
		"LastNameEng": "",
		"Name": "آتیه درمان و دندان صفرعلی زاده ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": "",
		"Email": "",
		"PhoneNumber": "",
		"Mobile": "",
		"AreaID": null,
		"DetailCode": "",
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": "",
		"Position": "",
		"NationalID": "",
		"RegistrationNumber": "",
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 14182,
		"Code": "6111231",
		"FromToNameAndCompany": "آدین شفیعی ",
		"FirstCompanyName": "آدین شفیعی",
		"LastName": "",
		"FirstCompanyNameEng": "",
		"LastNameEng": "",
		"Name": "آدین شفیعی ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": "",
		"Email": "",
		"PhoneNumber": "",
		"Mobile": "",
		"AreaID": null,
		"DetailCode": "",
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": "",
		"Position": "",
		"NationalID": "",
		"RegistrationNumber": "",
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 12793,
		"Code": "6110292",
		"FromToNameAndCompany": "آذر ابراهیمی فر ",
		"FirstCompanyName": "آذر ابراهیمی فر",
		"LastName": null,
		"FirstCompanyNameEng": "",
		"LastNameEng": null,
		"Name": "آذر ابراهیمی فر ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": "",
		"Email": "",
		"PhoneNumber": "",
		"Mobile": "",
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}, {
		"ID": 13781,
		"Code": "6110938",
		"FromToNameAndCompany": "آذر امامی ",
		"FirstCompanyName": "آذر امامی",
		"LastName": null,
		"FirstCompanyNameEng": "",
		"LastNameEng": null,
		"Name": "آذر امامی ",
		"NameEng": " ",
		"ProductID": 3,
		"Address": "",
		"Email": "",
		"PhoneNumber": "",
		"Mobile": "",
		"AreaID": null,
		"DetailCode": null,
		"Gender": true,
		"IsCompany": false,
		"NationalEconomicCode": null,
		"Position": null,
		"NationalID": null,
		"RegistrationNumber": null,
		"FromToID": null,
		"AreaCode": null,
		"AreaName": null,
		"AreaNameEng": null,
		"Active": true,
		"StateID": null,
		"State": null,
		"StateEng": null,
		"CityID": null,
		"City": null,
		"CityEng": null,
		"PostalCode": null,
		"CountCity": null,
		"CountyCityID": null,
		"RolesName": "مشتری",
		"CompanyName": null
	}]
"""


        val gson = Gson()
        val arrayCustomerType = object : TypeToken<Array<Customers>>() {}.type
        var arrayOfCustomer: Array<Customers> = gson.fromJson(customerJson, arrayCustomerType)
        var sliceCustomer = ArrayList<Customers>()
        val customeradaptor = CustomAdapter(sliceCustomer)
        binding.customerRecyclerview.adapter = customeradaptor
        binding.buttonNext.setOnClickListener {
            i = i + 2
            setData(arrayOfCustomer)
            println(setData(arrayOfCustomer)[0].Name)
            println(setData(arrayOfCustomer)[1].Name)
            sliceCustomer.clear()
            sliceCustomer.addAll(setData(arrayOfCustomer))
            customeradaptor.notifyDataSetChanged()
        }


    }

    fun setData(y: Array<Customers>): Array<Customers> {
        println("the i is $i")
        return y.sliceArray(i..i + 1)
    }


}